apiVersion: v1
kind: Service
metadata:
  name: {{ include "games-operator.fullname" . }}
  labels:
    {{- include "games-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "games-operator.selectorLabels" . | nindent 4 }}
---
# The Moonlight front door. Per-app stream Services created by the hub
# share this IP through the sharing key.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "games-operator.fullname" . }}-moonlight
  labels:
    {{- include "games-operator.labels" . | nindent 4 }}
  annotations:
    metallb.io/allow-shared-ip: {{ .Values.moonlight.sharingKey | quote }}
    lbipam.cilium.io/sharing-key: {{ .Values.moonlight.sharingKey | quote }}
    {{- with .Values.moonlight.loadBalancerIP }}
    metallb.io/loadBalancerIPs: {{ . | quote }}
    lbipam.cilium.io/ips: {{ . | quote }}
    {{- end }}
    {{- with .Values.moonlight.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: 47989
      targetPort: moonlight
      protocol: TCP
      name: moonlight
    - port: 47984
      targetPort: moonlight-tls
      protocol: TCP
      name: moonlight-tls
  selector:
    {{- include "games-operator.selectorLabels" . | nindent 4 }}
